"""add_recurring_expense_reminder_column

Revision ID: 2c8a8b5c259e
Revises: d42eadbc4d9b
Create Date: 2026-02-02 11:17:10.272875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8a8b5c259e'
down_revision: Union[str, None] = 'd42eadbc4d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('last_alert_date', sa.Date(), nullable=True))
    op.add_column('recurring_expenses', sa.Column('last_reminder_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('overall_monthly_limit', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'overall_monthly_limit')
    op.drop_column('recurring_expenses', 'last_reminder_date')
    op.drop_column('categories', 'last_alert_date')
    # ### end Alembic commands ###
