"""Add monthly_limit to categories

Revision ID: 5b6dba99e93c
Revises: 3e3d01d2b1bc
Create Date: 2026-02-01 18:28:18.651685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5b6dba99e93c'
down_revision: Union[str, None] = '3e3d01d2b1bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute('DROP TABLE IF EXISTS transfers')
    op.add_column('categories', sa.Column('monthly_limit', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'monthly_limit')
    op.create_table('transfers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_jar_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('to_jar_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('note', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_jar_id'], ['jars.id'], name='transfers_from_jar_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_jar_id'], ['jars.id'], name='transfers_to_jar_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='transfers_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='transfers_pkey')
    )
    op.create_index('ix_transfers_id', 'transfers', ['id'], unique=False)
    # ### end Alembic commands ###
