"""add multi currency columns

Revision ID: 79c943332269
Revises: 208628b5210f
Create Date: 2026-02-02 11:25:28.324963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c943332269'
down_revision: Union[str, None] = '208628b5210f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    expense_columns = [c['name'] for c in inspector.get_columns('expenses')]
    income_columns = [c['name'] for c in inspector.get_columns('incomes')]

    if 'original_amount' not in expense_columns:
        op.add_column('expenses', sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    if 'original_currency' not in expense_columns:
        op.add_column('expenses', sa.Column('original_currency', sa.String(length=3), nullable=True))
    if 'exchange_rate' not in expense_columns:
        op.add_column('expenses', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True))

    if 'original_amount' not in income_columns:
        op.add_column('incomes', sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    if 'original_currency' not in income_columns:
        op.add_column('incomes', sa.Column('original_currency', sa.String(length=3), nullable=True))
    if 'exchange_rate' not in income_columns:
        op.add_column('incomes', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'exchange_rate')
    op.drop_column('incomes', 'original_currency')
    op.drop_column('incomes', 'original_amount')
    op.drop_column('expenses', 'exchange_rate')
    op.drop_column('expenses', 'original_currency')
    op.drop_column('expenses', 'original_amount')
    # ### end Alembic commands ###
