"""add_budget_alert_columns

Revision ID: d42eadbc4d9b
Revises: b86ec14e1af6
Create Date: 2026-02-02 11:14:29.161928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd42eadbc4d9b'
down_revision: Union[str, None] = 'b86ec14e1af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
