"""restore_transfers_table

Revision ID: d8aaa1229a9d
Revises: 79c943332269
Create Date: 2026-02-02 11:37:46.593239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8aaa1229a9d'
down_revision: Union[str, None] = '79c943332269'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if table already exists just in case
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if 'transfers' not in tables:
        op.create_table('transfers',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('from_jar_id', sa.Integer(), nullable=False),
            sa.Column('to_jar_id', sa.Integer(), nullable=False),
            sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
            sa.Column('note', sa.String(length=255), nullable=True),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
            sa.ForeignKeyConstraint(['from_jar_id'], ['jars.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['to_jar_id'], ['jars.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.drop_table('transfers')
    # ### end Alembic commands ###
